---

language: python
python: "3.7"
sudo: required
dist: xenial

env:
  global:
    - ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/openmirror
    # SES_USERNAME
    - secure: "XdKk/I/OjhmyRPef8fUq+FitzU/reE6MrVGHSo9Q3hxqffZGk65xUgZI6ogSMZTOHZDR0mxzbioDk0hWfOhU0B2btGYrGkXmPc08cYqVjoAJyLDyMhwh/qAPV4oZaNMwHt/H0h7ms4zElWA/iOWqJXksbc8aN/nUFNxNvjkzB/Y2Ei5viBbDj8MwY5AAs9hKs71arfbZBaYpTAdcY9NaCtTrZ65L2641fKJxIIMM4IFH3Emw7AGmEdl6uDpJZeiXZkVgoYVadWBsi0L2bJoRv2U9YuQ+48Zb4av5L5YlzVcKrd1B69YxKstnRQLRDkRZZEd/4WoO2yzNKFe3YcPdRqokOe+eZlMUSxUvwr6UVFo7D48i7NgmsmY67ZTQ05IYlukJ8+3U/rXGf6uUQquhxyGvKAB/dOfQEXCjIgJUlyJNoPArfOr79Jc1MTs16WFmuEMLxeMvxaq3A0h6k4O25WtF3EQj6ougp1hStmR2CVPPxU26aStNey+t9OyzNlxzICvyxJ/T+C2q+45qqrhaQcIsjfazcZbKPHOaomwm95Vqu8QTUR02AkpHF+8YFIFwmiyUB0kBN0mBDEUMg2pxCnOyH7iEOUkE6kB93OVOfOJcaekRBmjQvFzsANv8yyqbZa/8EksLjVNa10qWlFdq30kgY4QN7C6MvLe1fwkzqPU="
    # SES_PASSWORD
    - secure: "Q4LuJSK1xwnIZ7jsFO6dY2yGAsICbuQeXvaCZ68iOevW06zKR+aWvrnpphmaOp9Ri7GE2e4sIE8g7AZS6UlApi4J1GSXGGdbvjwFoz3kkdmsM4JjLzxOjnVCFiV+UkCvlY8bLXydLjWIRsbOGUolGT1NjbNImuFvFnkcvSt5coYPI2kOm2Mm0Hn6BtqK6jUOqidKLbGlz72+3MCIH5Haet2P+2EV1csaCR9mViucLXcyjjFq2gkDmOQnOK5YNSkwqBfmhuH9COZPza06FV4OdbsEycCVHaDOsZNC81CPnhlgW39D1AiEfx3tCjiVhEDipaAYerOYGIIssdcFs5pw7iCzjE2Y31AaMdAv2rUEcCteUiUKJ6unKRsG0Z6ofd6DhIHyWk+GflMiAi9wYItgJMO5uEs2A4kMYXvBZsP0NMLX3PSPArwVlktCSg8V4L10kV6/+tnYPe+xZqwfyXJAkgZuvvZzYXFtVm17W+h1TftZs7z++H991rtEL+48lHroBFHuThV1eruDOlHwcWedlfCTbtiUiDc3Bl2expG/CyEI07z5sWQNzvvdLAPB4yLOTVtgUZPXB57Ly6SkIjxxXMSujhs43twnvVKSMCDi20TsUaEY/7eJomBOsiOC4Lv6eaHz0/DZ5TsmLju0+Hh1/fkOfkqD8qQaZVzBJx4I83A="

before_install:
  - mkdir -p ~/.ssh/

install:
  # Install ansible
  - sudo -H pip install ansible

  # Check ansible version
  - ansible --version

  - cat known_hosts >> ~/.ssh/known_hosts

script:
  - ./test.sh

deploy:
- provider: script
  script: ./provision.sh
  on:
    branch: master
  skip_cleanup: true
