---

language: python
python: "3.7"
sudo: required
dist: xenial

env:
  global:
    - ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/openmirror
    # SES_USERNAME
    - secure: "XdKk/I/OjhmyRPef8fUq+FitzU/reE6MrVGHSo9Q3hxqffZGk65xUgZI6ogSMZTOHZDR0mxzbioDk0hWfOhU0B2btGYrGkXmPc08cYqVjoAJyLDyMhwh/qAPV4oZaNMwHt/H0h7ms4zElWA/iOWqJXksbc8aN/nUFNxNvjkzB/Y2Ei5viBbDj8MwY5AAs9hKs71arfbZBaYpTAdcY9NaCtTrZ65L2641fKJxIIMM4IFH3Emw7AGmEdl6uDpJZeiXZkVgoYVadWBsi0L2bJoRv2U9YuQ+48Zb4av5L5YlzVcKrd1B69YxKstnRQLRDkRZZEd/4WoO2yzNKFe3YcPdRqokOe+eZlMUSxUvwr6UVFo7D48i7NgmsmY67ZTQ05IYlukJ8+3U/rXGf6uUQquhxyGvKAB/dOfQEXCjIgJUlyJNoPArfOr79Jc1MTs16WFmuEMLxeMvxaq3A0h6k4O25WtF3EQj6ougp1hStmR2CVPPxU26aStNey+t9OyzNlxzICvyxJ/T+C2q+45qqrhaQcIsjfazcZbKPHOaomwm95Vqu8QTUR02AkpHF+8YFIFwmiyUB0kBN0mBDEUMg2pxCnOyH7iEOUkE6kB93OVOfOJcaekRBmjQvFzsANv8yyqbZa/8EksLjVNa10qWlFdq30kgY4QN7C6MvLe1fwkzqPU="
    # SES_PASSWORD
    - secure: "G8vgdZNidk1ymrAj5+7TZoI7lscKUIgq0RSSJ71pSCS1SrSaTOAXClEUYJyNBdo6J5j21OFiKiOiOjMfuXrEe024JQGwRSr89t7NXuvtby2vn7+0t79L8+J/4EVues1cku+h24bUDBPemADEuEKuuNmorMOTkB4JX6IxygF4nQz2hYJxgoagOI7AgPJwhqjOpcsQDYUwsomRIVC7At6k5aomm85weO0TIp+iMTObfvW9xVSuI4u9pkJVFf3+VEyvDfX+df1JejXXag7+kHvE3L4QFH8krXBHPgqnCtbnVvd8U+V8lz7amijCVqUTEETxREW1dQZdQm5tAEGdKHfmaj5yCVbRxgUJ1zymaxsJ2wZGI9dvie1XnvJ0qJnMWaaa72sl7/ROvIIz5Psh03dk1U/ERAMB4Oa3XR2BX31eAknF+VgoHIxYqvDnY3tQaY3vN/5R/0XrYE3jggumEMjpsY7SHzk2j0yfW21/xVdxfuWDh6qmMnEq/9sLI5NkSwZSN4K6QbBBXYuyY/raJRpZzLLSonnyXZPcfC5/TVvfkOleZEySTcM8djxoP+Zd8ntx58sHa+VwHO477rD7xyaC0JGMSDpDF3VWe0OTrM6fk7fiBV8p9+bNLbnKbLwQIhPW1LAukMzdcCxinP2ug4ps55XkvhTUv2VsQg33nNl0cWU="

before_install:
  - openssl aes-256-cbc -K $encrypted_e18adef837ac_key -iv $encrypted_e18adef837ac_iv -in openmirror.enc -out ~/.ssh/openmirror -d

install:
  # Install ansible
  - sudo -H pip install ansible

  # Check ansible version
  - ansible --version
  
  - cat known_hosts >> ~/.ssh/known_hosts

script:
  - ./test.sh

deploy:
- provider: script
  script: ./provision.sh
  on:
    branch: master
  skip_cleanup: true
