---

language: python
python: "3.7"
sudo: required
dist: xenial

install:
  # Install ansible
  - sudo -H pip install ansible

  # Check ansible version
  - ansible --version
  
  - cat known_hosts >> ~/.ssh/known_hosts

script:
  - ./test.sh

deploy:
- provider: script
  script: ./provision.sh
  on:
    branch: master
  skip_cleanup: true
