---

- name: bare minimum
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - lsb-release
  become: yes

- name: update facts
  setup:

- name: upgrade system
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
