---

- name: bare minimum
  apt:
    name:
      - apt-transport-https
      - lsb-release
    state: present
  become: yes

- name: update facts
  setup:

- name: upgrade system
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
