---

- name: restart_rsyslog
  service:
    name: rsyslog
    state: restarted
  become: yes

- name: restart_munin_node
  service:
    name: munin-node
    state: restarted
    enabled: yes
  become: yes

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes
  become: yes

- name: restart_smartmontools
  service:
    name: smartmontools
    state: restarted
  become: yes

- name: restart_sshd
  service:
    name: ssh
    state: restarted
  become: yes
